posts/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug>/', views.group_posts, name='group'),
    path("new/", views.new_post, name="new_post"),

    # Профайл пользователя
    path("<username>/", views.profile, name="profile"),

    # Просмотр записи
    path('<username>/<int:post_id>/', views.post_view, name='post'),
    path("<username>/<int:post_id>/edit/", views.post_edit, name="post_edit"),
]

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")
]

yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.flatpages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("about/", include("django.contrib.flatpages.urls")),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
]

urlpatterns += [
    path('about-author/', views.flatpage, {'url': '/about-author/'}, name='author'),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'}, name='spec'),
]

urlpatterns += [
    path('about-us/', views.flatpage, {'url': '/about-us/'}, name='about'),
    path('terms/', views.flatpage, {'url': '/terms/'}, name='terms'),
]

posts/models.py
# из модуля db импортируем класс models
from django.db import models
# из модуля auth импортируем функцию get_user_model 
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True) 
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.title

class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True, related_name='posts')

    def __str__(self):
        return self.text

users/models.py
from django.db import models

# Create your models here.

posts/forms.py
from django import forms
from posts.models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('group', 'text')
        required = {'group': False, }
        widgets = {
            'text': forms.Textarea,
        }

users/forms.py
from typing import Set

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):

        model = User
        fields = {'first_name', "last_name", "username", "email"}

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.utils import timezone
from .models import Post, Group, User
from .forms import PostForm


def index(request):
    post_list = Post.objects.order_by('-pub_date').all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)

    return render(request, 'index.html', {'page': page,
                                          'paginator': paginator})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).order_by("-pub_date").all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    quantity = Post.objects.filter(group=group).count()
    return render(request, "group.html", {"group": group, "page": page,
                                          'paginator': paginator,
                                          'quantity': quantity})


@login_required
def new_post(request):
    button = "Создать"
    title = "Новая запись"
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['text']
            group = form.cleaned_data['group']
            author = request.user
            pub_date = timezone.now()
            post = Post.objects.create(text=text, pub_date=pub_date, author=author, group=group)
            return redirect('post:index')
        return render(request, "new_post.html", {"form": form, 'button': button, 'title': title})
    form = PostForm()
    return render(request, 'new_post.html', {'form':form, 'button': button, 'title': title})


def profile(request, username):
    profile = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=profile.pk)
    id_of_post = Post.objects.filter(author=profile.pk, id=None)
    posts_all = Post.objects.filter(author=profile).order_by('-pub_date').all()
    posts_count = posts_all.count()
    paginator = Paginator(post_list, 10)  # показывать по 10 записей на странице.
    page_number = request.GET.get('page')  # переменная в URL с номером запрошенной страницы
    page = paginator.get_page(page_number)  # получить записи с нужным смещением
    return render(request, "profile.html",
                  {"profile": profile, 'post_list': post_list, "count": posts_count, 'post_id': id_of_post,
                   'page': page, "paginator": paginator})


def post_view(request, username, post_id):
    # тут тело функции
    profile = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, author=profile.pk, id=post_id)
    count = Post.objects.filter(author=profile).count
    return render(request, "post.html", {"profile": profile, 'post': post, "count": count, })


def post_edit(request, username, post_id):
    profile = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, pk=post_id, author = profile.pk)
    button = "Сохранить"
    title = "Редактирование записи"
    if request.user.username != username:
        return redirect('post:post', username=post.author, post_id=post.pk)
    if request.method == "GET":
        form = PostForm(instance=post)
        return render(request, 'new_post.html', {'form': form, 'button': button, 'title': title, 'post': post})
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post:post', username=post.author, post_id=post.pk)
        return render(request, 'new_post.html', {'form': form, 'button': button, 'title': title, 'post': post})

users/views.py
from django.shortcuts import render

#  импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView

#  функция reverse_lazy позволяет получить URL по параметру "name" функции path()
#  берём, тоже пригодится
from django.urls import reverse_lazy

#  импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("login")
    template_name = "signup.html"

posts/templates/new_post.html
{% extends "base_post.html" %}
{% block title %} {% if edit %} Редактирование поста {% else %}Создание поста{% endif %} {% endblock %}
{% block header %} {% if edit %} Редактирование поста {% else %}Создание поста{% endif %}  {% endblock %}
{% block button %} {% if edit %} Редактировать {% else %} Добавить запись {% endif %} {% endblock %}

templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}Заголовок страницы{% endblock %} | Yatube</title>
        <!-- Загрузка статики -->
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        {% include 'nav.html' %}
        <main>
            <div class="container">
                {% block content %}
                <!-- Содержимое страницы -->
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}
</body>
</html>

templates/base_form.html
{% extends "base.html" %}

{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% block header %} {% endblock %}</div>
            <div class="card-body">

                <form method="post">
                    {% csrf_token %}

                    {% for field in form %}
                        {{ field.label}}
                        {{ field|addclass:"form-control" }}
                        
                        {% if field.errors %}
                        <p class="help-block"></p>
                            {% for error in field.errors %}
                            {{ error }}
                            {% endfor %}
                        </p>
                            {% endif %}
                        
                        {{ field.help_text | safe}}
                    {% endfor %}

                    <p>{{ value|linebreaksbr }}</p>

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                {% block button %} {% endblock %} 
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {{ year }}, все права защищены.</p>
</footer>

templates/group.html
{% extends "base.html" %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block content %}
    <h1>{{ group.title }}</h1>
    <p>
        {{ group.description }}
    </p>
    {% for post in page %}
    <h3>
        Автор: {{ post.author }}, дата публикации: {{ post.pub_date|date:'d M Y' }}
    </h3>
        <p>{{ post.text|linebreaksbr }}</p>
    {%endfor%}
    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
{% endblock content %}

templates/index.html
{% extends "base.html" %}
{% block title %} Последние обновления {% endblock %}
{% block content %}

    {% for post in page %}
    <h3>
        Автор: {{ post.author.get_full_name }}, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
        <p>{{ post.text|linebreaksbr }}</p>

        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                {% if user == post.author %}
                    <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{post.id}}/edit" role="button">Редактировать</a>
                {% else %}
                    <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{post.id}}" role="button">Просмотр</a>
                {% endif %}
            </div>
        </div>
    <hr>
    {% endfor %}

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}

{% endblock %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a href="/{{user.username}}/"> <strong class="p-2 text-gray-dark">{{user.username}}</strong> </a>
        <a class="p-2 text-dark" href="{% url 'post:new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/new_post.html
{% extends "base.html" %}

{% block title %} {{title}} {% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% block header %} {{title}} {% endblock %}</div>
            <div class="card-body">

                <form method="post">
                    {% csrf_token %}

                    {% block main_form %}
                        {% for field in form %}
                            {{ field.label}}
                            {{ field|addclass:"form-control" }}

                            {% if field.errors %}
                            <p class="help-block"></p>
                                {% for error in field.errors %}
                                {{ error }}
                                {% endfor %}
                            </p>
                                {% endif %}

                            {{ field.help_text | safe}}
                        {% endfor %}
                    {% endblock %}

                    <p>{{ value|linebreaksbr }}</p>

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% block button %} {{button}} {% endblock %}
                            </button>
                    </div>
                </form>

            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/paginator.html
<nav aria-label="Переключение страниц">
    <ul class="pagination">
        {% if items.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}">&laquo; Предыдущая</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Предыдущая</a></li>
        {% endif %}
        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(текущая)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}
        {% if items.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}">Следующая &raquo;</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

templates/post.html
{% extends "base.html" %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{profile.first_name}} {{profile.last_name}}
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     @{{profile.username}}
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписчиков: XXX <br />
                                        Подписан: XXX
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Количество записей -->
                                            Записей: {{count}}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->
                <div class="card mb-3 mt-1 shadow-sm">
                        <div class="card-body">
                                <p class="card-text">
                                        <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                        <a href="/{{profile.username}}/"><strong class="d-block text-gray-dark">@{{profile.username}}</strong></a>
                                        <!-- Текст поста -->
                                        <p>{{ post.text|linebreaksbr }}</p>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group ">
                                                <!-- Ссылка на редактирование, показывается только автору записи -->
                                                {% if request.user == post.author %}
                                                        <a class="btn btn-sm text-muted" href="{% url 'post:post_edit' username=request.user post_id=post.pk %}" role="button">Редактировать</a>
                                                {% endif %}
                                        </div>
                                        <!-- Дата публикации  -->
                                        <small class="text-muted">{{post.pub_date}}</small>
                                </div>
                        </div>
                </div>
     </div>
    </div>
</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        <!-- Имя автора -->
                                        {{profile.first_name}} {{profile.last_name}}
                                    </div>
                                    <div class="h3 text-muted">
                                         <!-- username автора -->
                                         @{{profile.username}}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: XXX <br />
                                            Подписан: XXX
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                <!-- Количество записей -->
                                                Записей: {{count}}
                                            </div>
                                    </li>
                            </ul>
                    </div>
            </div>

            <div class="col-md-9">

                <!-- Повторяющиеся записи -->
                {% for post in page %}
                <!-- Начало блока с отдельным постом -->
                    <div class="card mb-3 mt-1 shadow-sm">
                            <div class="card-body">
                                    <p class="card-text">
                                            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
                                            <a href="/{{profile.username}}/"><strong class="d-block text-gray-dark">@{{profile.username}}</strong></a>
                                            <!-- Текст поста -->
                                            <p>{{ post.text|linebreaksbr }}</p>

                                    </p>
                                    <div class="d-flex justify-content-between align-items-center">
                                            <div class="btn-group ">
                                                    <!-- Ссылка на страницу записи в атрибуте href-->
                                                    <a class="btn btn-sm text-muted" href="/{{profile.username}}/{{post_id}}/" role="button">Добавить комментарий</a>
                                                    <!-- Ссылка на редактирование, показывается только автору записи -->
                                                    {% if request.user == post.author %}
                                                        <a class="btn btn-sm text-muted" href="{% url 'post:post_edit' username=request.user post_id=post.pk %}" role="button">Редактировать</a>
                                                    {% endif %}
                                            </div>
                                            <!-- Дата публикации  -->
                                            <small class="text-muted">31 июля 1854 г. 0:00</small>
                                    </div>
                            </div>
                    </div>
                <!-- Конец блока с отдельным постом -->
                <!-- Остальные посты -->
                {% endfor %}
                <!-- Здесь постраничная навигация паджинатора -->
                {% if page.has_other_pages %}
                        {% include "paginator.html" with items=page paginator=paginator%}
                {% endif %}
     </div>
    </div>
</main>
{% endblock %}

users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">

                    {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                    {% endfor %}


                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}